### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by gzw820** [wenyyu/Image-Adaptive-YOLO#10]
When I try to reproduce this result according to the quick start instructions, something is wrong with this code.
![Screenshot from 2021-12-28 20-56-28](https://user-images.githubusercontent.com/72793442/147576987-41f630be-4138-4135-9038-dd68fbd371e7.png)

Could you help me? Thank you!

**Comment by wenyyu** [comment]
Our project doesn't use this function, so you can just delete it.

**Comment by yxx-byte** [comment]
你好，请问你已经训练好了吗，我按照readme操作，但是训练没有反应
![image](https://user-images.githubusercontent.com/73935151/147623384-4c84b393-f4af-4402-b33f-84afd3c6b683.png)

**Comment by gzw820** [comment]
我没有重新训练



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月29日(星期三) 中午11:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wenyyu/Image-Adaptive-YOLO] code problem (Issue #10)





 
你好，请问你已经训练好了吗，我按照readme操作，但是训练没有反应
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
