### ISSUE TITLE
请问‘epoch_first_stage’和'epoch_second_stage'这两个参数的含义是什么呢？

### ISSUE THREAD

**Issue by pumpkin29** [wenyyu/Image-Adaptive-YOLO#11]
您好，请问train.py中‘epoch_first_stage’和'epoch_second_stage'这两个参数的含义是什么呢？我不清楚第一阶段和第二阶段指的是什么，请问是指的DIP模块和yolov3吗？
![image](https://user-images.githubusercontent.com/70458654/147580446-32702747-b3d7-4bb3-aaf4-d8124d68aab2.png)

**Comment by wenyyu** [comment]
你好，‘epoch_first_stage‘为训练只更新某些参数的轮数，’epoch_second_stage‘为第二阶段更新所有参数训练的轮数，详细请看train.py里的设置。目前实际训练中没有用到epoch_first_stage，默认设置为0。

**Comment by mvpzhangqiu** [comment]
> 你好，‘epoch_first_stage‘为训练只更新某些参数的轮数，’epoch_second_stage‘为第二阶段更新所有参数训练的轮数，详细请看train.py里的设置。目前实际训练中没有用到epoch_first_stage，默认设置为0。

总共的epoch在哪里设置？
