### ISSUE TITLE
训练不起来

### ISSUE THREAD

**Issue by yxx-byte** [wenyyu/Image-Adaptive-YOLO#13]
你好，博主，我生成了自己的voc_annotation.py ,修改了data_make.py，config.py里面的路径，但是训练不起来。
![image](https://user-images.githubusercontent.com/73935151/147623553-4d02ab88-de86-422c-9af9-3fa522488728.png)
![image](https://user-images.githubusercontent.com/73935151/147623575-d78b7401-213d-4b55-9326-aced0797c2c9.png)
![image](https://user-images.githubusercontent.com/73935151/147623599-9208851e-1820-4c31-9676-807952d3b25d.png)
![image](https://user-images.githubusercontent.com/73935151/147623637-2aad7a48-303f-4bcf-8f65-b169b69e9716.png)

**Comment by wenyyu** [comment]
你好，你参照下论文，同时修改相关路径，根据报的错误，一步一步调试好。另外，有啥问题可以通过邮箱（liuwenyu.lwy@zju.edu.cn）联系我。谢谢

**Comment by pumpkin29** [comment]
> 你好，你参照下论文，同时修改相关路径，根据报的错误，一步一步调试好。另外，有啥问题可以通过邮箱（[liuwenyu.lwy@zju.edu.cn](mailto:liuwenyu.lwy@zju.edu.cn)）联系我。谢谢

您好，请问如果我想使用您所提供的权重文件接着往后训练的话，应该修改哪些参数呢？（比如说，已经训练了40个epoch，但是训练停止了，然后想从第41个epoch开始接着再往后训练20个epoch。）我的想法是：修改config.py，将第40个epoch所得到的权重作为initial_weight读入，将epoch_first_stage设为0，epoch_second_stage设为20。请问这样可以吗
