### ISSUE TITLE
从某个epoch开始接着往后训练

### ISSUE THREAD

**Issue by pumpkin29** [wenyyu/Image-Adaptive-YOLO#14]
您好，请问如果我想从某个epoch开始接着往后训练的话，应该如何修改呢？（比如说，已经训练了40个epoch，但是训练停止了，然后想从第41个epoch开始接着再往后训练20个epoch。）我的想法是：修改config.py，将第40个epoch所得到的权重作为initial_weight读入，将epoch_first_stage设为0，epoch_second_stage设为20。请问这样可以吗

**Comment by wenyyu** [comment]
你好，可以的。在config.py 修改args.pre_train 加载预训练模型即可。

**Comment by pumpkin29** [comment]
> 你好，可以的。在config.py 修改args.pre_train 加载预训练模型即可。

好的，谢谢您
