### ISSUE TITLE
about train data

### ISSUE THREAD

**Issue by frensher** [wenyyu/Image-Adaptive-YOLO#15]
你好，我想问下，表格中的train data 的VOC_norm指的是正常光照下的voc数据吗？
还有下面的hybrid data数据怎么理解呢，混合了voc数据和exdark数据吗，是不是混合数据里面既有正常关照和弱光的数据啊？

**Comment by wenyyu** [comment]
你好，请结合论文和最新代码理解，都有比较详细的说明。
