### ISSUE TITLE
暗光情况评估结果不符

### ISSUE THREAD

**Issue by Yuxin-Yu** [wenyyu/Image-Adaptive-YOLO#16]
您好，我用您的成果分别去验证了大雾和暗光条件下的识别情况，在大雾情况下的验证结果符合论文中的结论，达到了72%的平均识别率。但是对于暗光条件的三个测试集出现了结果严重不符的情况，VOC_norm_test，VOC_Dark_test和Exdark_test平均精度分别如下：
![image](https://user-images.githubusercontent.com/38584421/147846785-99905024-909f-4b3e-b31d-72fa7f03bee1.png)
![image](https://user-images.githubusercontent.com/38584421/147846790-93461f40-fdd9-4d1d-853f-fef4ff27a7ac.png)
![image](https://user-images.githubusercontent.com/38584421/147846797-a0bf7592-be91-46ee-b351-5203a5c6e3b1.png)
我只改了config_lowlight中的test_path路径，不知道是我操作的问题还是提供的权重有问题。另外就是我是用的TensorFlow2版本跑的您的代码，将您的代码做了TensorFlow2的适配。想问下您觉得大概率是哪里的问题呢。

**Comment by Yuxin-Yu** [comment]
我后面用最新的代码跑了下，结果没问题。打扰了

**Comment by yummy0109** [comment]
你好请问一下，在雾天情况下，离线生成val图像如何生成，作者没有提供voc_norm_val.txt文件。

**Comment by yummy0109** [comment]
> 我后面用最新的代码跑了下，结果没问题。打扰了

https://github.com/wenyyu/Image-Adaptive-YOLO/issues/16#issuecomment-1003657879

> 我后面用最新的代码跑了下，结果没问题。打扰了

你好请问一下，在雾天情况下，离线生成val图像如何生成，作者没有提供voc_norm_val.txt文件。
