### ISSUE TITLE
about loss function

### ISSUE THREAD

**Issue by frensher** [wenyyu/Image-Adaptive-YOLO#18]
你好，我想问下，针对前面的各种图像数据处理，不需要损失函数进行约束吗

**Comment by pumpkin29** [comment]
我觉得应该是这个损失吧https://github.com/wenyyu/Image-Adaptive-YOLO/blob/main/core/yolov3.py#L77

**Comment by wenyyu** [comment]
你好，我们是针对整个pipeline进行端到端地以优化detection loss进行训练的，对DIP模块不设单独的loss进行约束。

**Comment by pumpkin29** [comment]
> 你好，我们是针对整个pipeline进行端到端地以优化detection loss进行训练的，对DIP模块不设单独的loss进行约束。

请问这个recovery_loss是和CNN-PP网络有关系吧？将filters处理过的图像和原本的normal图像计算损失recovery_loss，然后将recovery_loss和yolov3的损失一起对整个网络进行约束，请问是这样理解吗？
![image](https://user-images.githubusercontent.com/70458654/148328096-be5aaf83-8ee9-473f-87b0-52b177fba12c.png)

**Comment by wenyyu** [comment]
训练的total_loss并没有包含recovery_loss。参照train.py。你也可以多做做一些实验，看看加入该loss效果如何。谢谢。

**Comment by pumpkin29** [comment]
> 训练的total_loss并没有包含recovery_loss。参照train.py。你也可以多做做一些实验，看看加入该loss效果如何。谢谢。

好的，谢谢您
