### ISSUE TITLE
about dataset_dark

### ISSUE THREAD

**Issue by frensher** [wenyyu/Image-Adaptive-YOLO#19]
你好，这个弱光数据集下的voc_norm_train.txt是16000+图片，跟论文中的12000+对不上 啊，是不是记事本文件提供错了

**Comment by wenyyu** [comment]
你好，在读取图片训练时，会只选择含有相应类别的图片加入训练，详见 ./core/dataset.py.

**Comment by frensher** [comment]
你好，能说的具体点吗，我还不是很清楚

**Comment by frensher** [comment]
> 你好，在读取图片训练时，会只选择含有相应类别的图片加入训练，详见 ./core/dataset.py.

你好，能具体说些吗，抱歉，我还是没有看出来
