### ISSUE TITLE
CNN-PP模块的网络结构讨论

### ISSUE THREAD

**Issue by pumpkin29** [wenyyu/Image-Adaptive-YOLO#20]
您好，请问CNN-PP网络为什么要这样设计呢？请问您有试过6层卷积层吗？

**Comment by wenyyu** [comment]
> 您好，请问CNN-PP网络为什么要这样设计呢？请问您有试过6层卷积层吗？

你好，CNN-PP是一个轻量级的小网络，用于预测DIP模块的参数，因此设计得比较轻巧。
