### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by frensher** [wenyyu/Image-Adaptive-YOLO#21]
你好，能分享下RTTS数据集的链接吗，官网的链接过期了，谢谢

**Comment by wenyyu** [comment]
> 你好，能分享下RTTS数据集的链接吗，官网的链接过期了，谢谢

你好，根据此链接下载。[RTTS](https://sites.google.com/view/reside-dehaze-datasets/reside-%CE%B2)

**Comment by frensher** [comment]
> > 你好，能分享下RTTS数据集的链接吗，官网的链接过期了，谢谢
> 
> 你好，根据此链接下载。[RTTS](https://sites.google.com/view/reside-dehaze-datasets/reside-%CE%B2)

谢谢啦

**Comment by frensher** [comment]
> > 你好，能分享下RTTS数据集的链接吗，官网的链接过期了，谢谢
> 
> 你好，根据此链接下载。[RTTS](https://sites.google.com/view/reside-dehaze-datasets/reside-%CE%B2)

谢谢
