### ISSUE TITLE
论文中的雾天图像

### ISSUE THREAD

**Issue by WhXl** [wenyyu/Image-Adaptive-YOLO#22]
关于雾天图像的定义是论文中的（10），（11）公式，即

![2022-01-23 09-22-20屏幕截图](https://user-images.githubusercontent.com/50477520/150661045-6f76e6d4-79c8-42ad-9e88-d1234818d4e8.png)

但是在代码中的定义为:
`self.input_data: np.power(train_data[0], lowlight_param),# train_data[0]*np.exp(lowlight_param*np.log(2)),`
请问为什么这样去实现

**Comment by wenyyu** [comment]
> 关于雾天图像的定义是论文中的（10），（11）公式，即
> 
> ![2022-01-23 09-22-20屏幕截图](https://user-images.githubusercontent.com/50477520/150661045-6f76e6d4-79c8-42ad-9e88-d1234818d4e8.png)
> 
> 但是在代码中的定义为: `self.input_data: np.power(train_data[0], lowlight_param),# train_data[0]*np.exp(lowlight_param*np.log(2)),` 请问为什么这样去实现

你好，你截取的代码是针对low-light场景的。
