### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by xkai957** [wenyyu/Image-Adaptive-YOLO#29]
在训练自己的数据集时出现索引超出范围，一直没搞明白怎么回事
![Snipaste_2022-03-18_22-49-36](https://user-images.githubusercontent.com/56034103/159025598-b449e85a-2f65-470a-b5bf-8eb1a39af543.jpg)

**Comment by xkai957** [comment]
我已经解决了

**Comment by mvpzhangqiu** [comment]
> 我已经解决了

哥 我也是训练自己的数据集出现这个问题，请问您是怎么解决的？

**Comment by mvpzhangqiu** [comment]
> 我已经解决了

@xkai957 兄弟
