### ISSUE TITLE
数据生成

### ISSUE THREAD

**Issue by XuKer** [wenyyu/Image-Adaptive-YOLO#30]
你好，请问下 python ./core/data_make.py 生成的vocfog 数据train和val。我这边的程序怎么一直都在生成，train目录两万多张，最后卡死了，被系统杀掉进程。val也一万多张了，还在进行中。这种情况是正确的吗？

**Comment by pumpkin29** [comment]
> 你好，请问下 python ./core/data_make.py 生成的vocfog 数据train和val。我这边的程序怎么一直都在生成，train目录两万多张，最后卡死了，被系统杀掉进程。val也一万多张了，还在进行中。这种情况是正确的吗？
因为1张训练/验证图片会对应生成10张雾图

**Comment by XuKer** [comment]
> > 你好，请问下 python ./core/data_make.py 生成的vocfog 数据train和val。我这边的程序怎么一直都在生成，train目录两万多张，最后卡死了，被系统杀掉进程。val也一万多张了，还在进行中。这种情况是正确的吗？
> > 因为1张训练/验证图片会对应生成10张雾图

好的，多谢

**Comment by saucycie** [comment]
您好， 运行data_make的时候,程序一直在运行， 但是没有生成图片
![image](https://user-images.githubusercontent.com/102406982/160229935-d1913f24-9c94-401d-b164-e8ec15a2f161.png)

是什么原因呢

**Comment by XuKer** [comment]
> ak

这个是在一直生成图片

**Comment by saucycie** [comment]
首先感谢您的回信，可是我在对应文件夹没有看到有图片生成

**Comment by lunn28265** [comment]
> 首先感谢您的回信，可是我在对应文件夹没有看到有图片生成
> […](#)  [...](#)

你好，我也是在对应的文件夹下没有看到图片生成，请问你最后解决了吗？
