### ISSUE TITLE
about map

### ISSUE THREAD

**Issue by frensher** [wenyyu/Image-Adaptive-YOLO#31]
你好，我想问下，您的yolov3用没用预训练模型呢？为什么正常数据的map值很低呢，低于其他文献的正常水平

**Comment by wenyyu** [comment]
你好，Baseline YOLOv3 和Our IA-YOLO均是trained  from scratch，MAP结果参考我们论文。谢谢

**Comment by frensher** [comment]
> 你好，Baseline YOLOv3 和Our IA-YOLO均是trained from scratch，MAP结果参考我们论文。谢谢

为什么没有加载预训练模型呢，是有什么特殊的考量吗
