### ISSUE TITLE
请问如何用voc数据集生成低光线下的图，看代码项目里面没有提供相应脚本。只提供了生成雾天的脚本

### ISSUE THREAD

**Issue by axiaoxiaobai** [wenyyu/Image-Adaptive-YOLO#32]

**Comment by wenyyu** [comment]
你好，暗光数据是训练时在线生成的，详见代码。

**Comment by mvpzhangqiu** [comment]
> 你好，暗光数据是训练时在线生成的，详见代码。
你好，想问下这部分代码在哪块，找不着...

**Comment by mvpzhangqiu** [comment]
> > 你好，暗光数据是训练时在线生成的，详见代码。
> > 你好，想问下这部分代码在哪块，找不着...

self.input_data: np.power(train_data[0], lowlight_param),# train_data[0]*np.exp(lowlight_param*np.log(2))

train_lowlight.py文件里头这行是吧？
