### ISSUE TITLE
lowlight数据集

### ISSUE THREAD

**Issue by nningxuan** [wenyyu/Image-Adaptive-YOLO#34]
您好，我看你的代码里只有雾天数据集的生成方式，请教一下弱光的数据集是怎么生成的

**Comment by wenyyu** [comment]
你好，暗光数据是在线生成的。

**Comment by yuzhijia1997** [comment]
> 你好，暗光数据是在线生成的。

您好，请问一下暗光数据是怎么在线生成的呢？似乎没有这部分的代码
