### ISSUE TITLE
gpu训练慢

### ISSUE THREAD

**Issue by jijiangyan** [wenyyu/Image-Adaptive-YOLO#36]
您好，感谢您提供如此优秀的代码，有个问题想向您请教一下，训练我在config.py选择使用gpu，但是训练特别慢，gpu显存占用也比较少，只有253MB.是不是我有别的地方没有修改？期待您的回复

**Comment by shgrace233** [comment]
您好，我也遇到这个问题，请问你是怎么解决的呢？感谢

**Comment by shgrace233** [comment]
我知道了，我的问题是因为安装的cuda、cudnn的版本与代码的tensorflow-gpu的版本不对应导致训练并未使用gpu而是用的cpu在训，重新安装好对应的版本，训练速度和显存占用就提上去了。

**Comment by 7W7W7W** [comment]
我也是这个问题，用不上GPU，但是我是30显卡，只能cuda11以上就很烦
