### ISSUE TITLE
关于测试集VOC_Foggy_test dataset

### ISSUE THREAD

**Issue by lzhhha** [wenyyu/Image-Adaptive-YOLO#37]
您好，这个测试集VOC_Foggy_test dataset是所有不同浓度的雾图(27340张)，还是随机一种浓度的雾图呢(2734张)？

**Comment by wenyyu** [comment]
你好，是所有图像随机选择一种浓度组成的2734张图像。readme里给了VOC_Foggy_test dataset 下载链接。

**Comment by lzhhha** [comment]
> 你好，是所有图像随时选择一种浓度组成的2734张图像。读我里给了VOC_Foggy_test dataset 下载。

**Comment by lzhhha** [comment]
好的谢谢

**Comment by lzhhha** [comment]
好的谢谢
