### ISSUE TITLE
关于VOC_Foggy_test

### ISSUE THREAD

**Issue by lzhhha** [wenyyu/Image-Adaptive-YOLO#38]
您好，我看到readme中给的百度云链接中的VOC_Foggy_test测试集中图像数量不是2734张，为4952张，这个是为什么呢，我在测试时是用这4952张图像作为测试集吗？

**Comment by wenyyu** [comment]
> 

你好，VOC__test本身时有4952张图像，但是测试时，我们只测试包含训练的五类对象（person, bicycle, car, bus
and motorcycle）的2734张图像。我们是在测试代码中筛选出这2734张图像的，忘记在测试集中筛选了，不好意思。

**Comment by wenyyu** [comment]
你好，通过‘./data/dataset_fog/voc_fog_test.txt'读取2734张VOC_Foggy_test测试集图像。
