### ISSUE TITLE
Error reporting problem of util_filter.py file

### ISSUE THREAD

**Issue by Yuxin-Yu** [wenyyu/Image-Adaptive-YOLO#4]
When I run the code python evaluate.py, it shows that there is a syntax error in line 658 of util_filter.py. What are these codes for? It’s okay to delete them.
![image](https://user-images.githubusercontent.com/38584421/147073624-8909a2f3-632c-452f-b8e5-daaca5d89b8e.png)

**Comment by wenyyu** [comment]
Hi, you can just delete them.
