### ISSUE TITLE
关于验证集的生成问题

### ISSUE THREAD

**Issue by yummy0109** [wenyyu/Image-Adaptive-YOLO#45]
运行data_make.py只生成了训练集，并且代码也只有voc_norm_train.txt，相应的文件夹也没有voc_norm_val.txt，那么该如何生成验证集呢？（测试集是要把注释去掉，重新运行一遍data_make.py吗？）
![image](https://user-images.githubusercontent.com/106219735/173181966-f4230d52-1014-496d-80a2-e674757bb891.png)

**Comment by xiejiadiwu** [comment]
您好 我也在因为这个问题而纠结 ，请问您解决吗？

**Comment by yummy0109** [comment]
> 

我运行了两遍data_make.py，分别生成了测试集和验证集，voc_norm_test.txt是用来生成验证集

**Comment by xiejiadiwu** [comment]
好的 谢谢
