### ISSUE TITLE
> 81110多张train,27340张val

### ISSUE THREAD

**Issue by TDlemon-1900** [wenyyu/Image-Adaptive-YOLO#52]
> 81110多张train,27340张val

你的python版本和conda环境能截个图吗，我这边包有冲突，也不知道是哪里问题。

_Originally posted by @XuKer in https://github.com/wenyyu/Image-Adaptive-YOLO/issues/28#issuecomment-1075799117_

**Comment by 123ERFW** [comment]
你好，打扰您
我在运行data_make.py的时候运行了很久没有反应，想问一下，在这个文件中的两个路径是否都需要修改，他们保存在了哪个路径下面？感谢您！
