### ISSUE TITLE
.

### ISSUE THREAD

**Issue by andwizard** [wenyyu/Image-Adaptive-YOLO#66]
you can see my code here
[https://github.com/andwizard/adaptive-yolov5](url)

**Comment by Xiaobaicai13** [comment]
Hello, excuse me, can I have a look at your pytorch version of the code.

**Comment by andwizard** [comment]
> 

可以，咋给你看

**Comment by andwizard** [comment]
> Hello, excuse me, can I have a look at your pytorch version of the code.

可以，咋给你看，我这上传不了github

**Comment by Xiaobaicai13** [comment]
感谢回复，加QQ或者微信传文件看行不？
&nbsp;


杨鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月4日(星期四) 下午3:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorch and yolov5, but it`s gradient cannot propagate properly (Issue #66)





  
Hello, excuse me, can I have a look at your pytorch version of the code.
  
可以，咋给你看，我这上传不了github

**Comment by andwizard** [comment]
数字屏蔽了，过会我看看能不能上传github,或者你有啥问题直接问


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wenyyu/Image-Adaptive-YOLO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月4日(星期四) 下午3:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorch and yolov5, but it`s gradient cannot propagate properly (Issue #66)





 感谢回复，加QQ或者微信传文件看行不？ 
 &amp;nbsp; 
 
 
 杨鹏 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2023年5月4日(星期四) 下午3:23 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorch and yolov5, but it`s gradient cannot propagate properly (Issue #66) 
 
 
 
 
 
    
 Hello, excuse me, can I have a look at your pytorch version of the code. 
    
 可以，咋给你看，我这上传不了github

**Comment by Xiaobaicai13** [comment]
您看看能不能上传github，万分感谢。


杨鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wenyyu/Image-Adaptive-YOLO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月4日(星期四) 下午4:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorch and yolov5, but it`s gradient cannot propagate properly (Issue #66)





 数字屏蔽了，过会我看看能不能上传github,或者你有啥问题直接问 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "wenyyu/Image-Adaptive-YOLO"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年5月4日(星期四) 下午3:49 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorch and yolov5, but it`s gradient cannot propagate properly (Issue #66) 
 
 
 
 
 
  感谢回复，加QQ或者微信传文件看行不？  
  &amp;amp;nbsp;  
   
   
  杨鹏  
  ***@***.***  
   
   
   
  &amp;amp;nbsp;  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2023年5月4日(星期四) 下午3:23  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  主题: Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorch and yolov5, but it`s gradient cannot propagate properly (Issue #66)  
   
   
   
   
   
      
  Hello, excuse me, can I have a look at your pytorch version of the code.  
      
  可以，咋给你看，我这上传不了github

**Comment by andwizard** [comment]
你加我这个邮箱的qq，我上传到github有问题



---Original---
From: ***@***.***&gt;
Date: Thu, May 4, 2023 16:03 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorchand yolov5, but it`s gradient cannot propagate properly (Issue #66)




 您看看能不能上传github，万分感谢。 
 
 
 杨鹏 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "wenyyu/Image-Adaptive-YOLO"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年5月4日(星期四) 下午4:00 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorch and yolov5, but it`s gradient cannot propagate properly (Issue #66) 
 
 
 
 
 
  数字屏蔽了，过会我看看能不能上传github,或者你有啥问题直接问  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "wenyyu/Image-Adaptive-YOLO"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2023年5月4日(星期四) 下午3:49  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorch and yolov5, but it`s gradient cannot propagate properly (Issue #66)  
   
   
   
   
   
   感谢回复，加QQ或者微信传文件看行不？   
   &amp;amp;amp;nbsp;   
     
     
   杨鹏   
   ***@***.***   
     
     
     
   &amp;amp;amp;nbsp;   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人: ***@***.***&amp;amp;amp;gt;;    
   发送时间: 2023年5月4日(星期四) 下午3:23   
   收件人: ***@***.***&amp;amp;amp;gt;;    
   抄送: ***@***.***&amp;amp;amp;gt;; ***@***.***&amp;amp;amp;gt;;    
   主题: Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorch and yolov5, but it`s gradient cannot propagate properly (Issue #66)   
     
     
     
     
     
        
   Hello, excuse me, can I have a look at your pytorch version of the code.   
        
   可以，咋给你看，我这上传不了github

**Comment by songshengli-123** [comment]
@andwizard 请问可以分享一下torch版本的么？

**Comment by XJWang628** [comment]
> 主题: Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorch and yolov5, but it`s gradient cannot propagate properly (Issue #66)

Hi, can you share the code of torch version? My email address is 861359518@qq.com.

**Comment by XJWang628** [comment]
> you can see my code here [https://github.com/andwizard/adaptive-yolov5](url)

Hi, can you share the code of torch version? My email address is [861359518@qq.com](mailto:861359518@qq.com).

**Comment by Xiaobaicai13** [comment]
兄弟，这里不显示你的qq，你的主页也没有这个代码，怎么加你


杨鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wenyyu/Image-Adaptive-YOLO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月6日(星期六) 下午5:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorch and yolov5, but it`s gradient cannot propagate properly (Issue #66)





 你加我这个邮箱的qq，我上传到github有问题 
 
 
 
 ---Original--- 
 From: ***@***.***&amp;gt; 
 Date: Thu, May 4, 2023 16:03 PM 
 To: ***@***.***&amp;gt;; 
 Cc: ***@***.******@***.***&amp;gt;; 
 Subject: Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorchand yolov5, but it`s gradient cannot propagate properly (Issue #66) 
 
 
 
 
  您看看能不能上传github，万分感谢。  
   
   
  杨鹏  
  ***@***.***  
   
   
   
  &amp;amp;nbsp;  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "wenyyu/Image-Adaptive-YOLO"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2023年5月4日(星期四) 下午4:00  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorch and yolov5, but it`s gradient cannot propagate properly (Issue #66)  
   
   
   
   
   
   数字屏蔽了，过会我看看能不能上传github,或者你有啥问题直接问   
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "wenyyu/Image-Adaptive-YOLO"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2023年5月4日(星期四) 下午3:49   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorch and yolov5, but it`s gradient cannot propagate properly (Issue #66)   
     
     
     
     
     
    感谢回复，加QQ或者微信传文件看行不？    
    &amp;amp;amp;amp;nbsp;    
       
       
    杨鹏    
    ***@***.***    
       
       
       
    &amp;amp;amp;amp;nbsp;    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人: ***@***.***&amp;amp;amp;amp;gt;;     
    发送时间: 2023年5月4日(星期四) 下午3:23    
    收件人: ***@***.***&amp;amp;amp;amp;gt;;     
    抄送: ***@***.***&amp;amp;amp;amp;gt;; ***@***.***&amp;amp;amp;amp;gt;;     
    主题: Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorch and yolov5, but it`s gradient cannot propagate properly (Issue #66)    
       
       
       
       
       
          
    Hello, excuse me, can I have a look at your pytorch version of the code.    
          
    可以，咋给你看，我这上传不了github

**Comment by XJWang628** [comment]
> 兄弟，这里不显示你的qq，你的主页也没有这个代码，怎么加你 杨鹏 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wenyyu/Image-Adaptive-YOLO" ***@***.***&gt;; 发送时间:&nbsp;2023年5月6日(星期六) 下午5:30 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorch and yolov5, but it`s gradient cannot propagate properly (Issue #66) 你加我这个邮箱的qq，我上传到github有问题
> ---Original--- From: ***@***.***&amp;gt; Date: Thu, May 4, 2023 16:03 PM To: ***@***.***&amp;gt;; Cc: ***@***.******@***.***&amp;gt;; Subject: Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorchand yolov5, but it`s gradient cannot propagate properly (Issue #66) 您看看能不能上传github，万分感谢。 杨鹏 ***@***.*** &amp;amp;nbsp;
> ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------ 发件人: "wenyyu/Image-Adaptive-YOLO" ***@***.***&amp;amp;gt;; 发送时间:&amp;amp;nbsp;2023年5月4日(星期四) 下午4:00 ***@***.***&amp;amp;gt;; ***@***.******@***.***&amp;amp;gt;; 主题:&amp;amp;nbsp;Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorch and yolov5, but it`s gradient cannot propagate properly (Issue #66) 数字屏蔽了，过会我看看能不能上传github,或者你有啥问题直接问
> ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------ 发件人: "wenyyu/Image-Adaptive-YOLO" ***@***.***&amp;amp;amp;gt;; 发送时间:&amp;amp;amp;nbsp;2023年5月4日(星期四) 下午3:49 ***@***.***&amp;amp;amp;gt;; ***@***.******@***.***&amp;amp;amp;gt;; 主题:&amp;amp;amp;nbsp;Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorch and yolov5, but it`s gradient cannot propagate properly (Issue #66) 感谢回复，加QQ或者微信传文件看行不？ &amp;amp;amp;amp;nbsp; 杨鹏 ***@***.*** &amp;amp;amp;amp;nbsp;
> ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------ 发件人: ***@***.***&amp;amp;amp;amp;gt;; 发送时间: 2023年5月4日(星期四) 下午3:23 收件人: ***@***.***&amp;amp;amp;amp;gt;; 抄送: ***@***.***&amp;amp;amp;amp;gt;; ***@***.***&amp;amp;amp;amp;gt;; 主题: Re: [wenyyu/Image-Adaptive-YOLO] I try to implement this by pytorch and yolov5, but it`s gradient cannot propagate properly (Issue #66) Hello, excuse me, can I have a look at your pytorch version of the code. 可以，咋给你看，我这上传不了github — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&amp;amp;amp;amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&amp;amp;amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&amp;amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

感谢回复，我的邮箱是861359518@qq.com，麻烦您给我发一份pytorch版本的代码。

**Comment by Liangmf11** [comment]
@andwizard 您好，请问可以提供一下您的邮箱吗？或者麻烦您也发给我一份pytorch版本的代码，谢谢！我的邮箱是liangm17@mcmaster.ca

**Comment by aowuaaa** [comment]
您好，请问可以分享您的pytorch版本的代码吗，十分感谢。
我的邮箱是202986246@qq.com
