### ISSUE TITLE
about Sharpen Filter

### ISSUE THREAD

**Issue by frensher** [wenyyu/Image-Adaptive-YOLO#7]
作者你好，很欣赏您的工作。我想问下，我看看各种滤波器的文件，但是我没有看到锐化操作的函数，能指明下吗

**Comment by wenyyu** [comment]
你好，见 filter.py 中 class UsmFilter(Filter).

**Comment by frensher** [comment]
> 你好，见 filter.py 中 class UsmFilter(Filter).

好的，谢谢
