### ISSUE TITLE
request

### ISSUE THREAD

**Issue by yxx-byte** [wenyyu/Image-Adaptive-YOLO#9]
你好，我的代码配置了requirement的环境配置，载入IA-YOLO数据集，但是我train不起来，你可以解答一下吗？
![Uploading image.png…]()

**Comment by yxx-byte** [comment]
我的QQ：2532070242，你方便联系我吗？15082752383

**Comment by yxx-byte** [comment]
文玉，代码里面导入了IA-YOLO数据集，但是没有标注，使用原先你生成的txt文件，但路径是错误的。现在应该怎么办呢

**Comment by wenyyu** [comment]
你好，跟路径相关的文件，记得改成你的相应路径下。谢谢。

**Comment by yxx-byte** [comment]
感谢你的及时回复，image_path一直报是你的，txt文件的也不对，具体是在哪里修改呢，文玉，你方便加下你的联系方式吗？我目前正在学习研读你的代码，万分感谢

**Comment by wenyyu** [comment]
你好，参照  scripts/voc_annotation.py  运行生成你自己的路径文件， README.md 有详细流程。谢谢

**Comment by yxx-byte** [comment]
还是没能够生成，如图所示，在voc_annotation.py
![image](https://user-images.githubusercontent.com/73935151/147576670-60b74533-773b-4528-b7d8-a62912515122.png)

**Comment by yxx-byte** [comment]
h还望能多多指教

**Comment by yxx-byte** [comment]
博主，你好，上面图片中的问题是缺少了flags.train_annotation，
